variables :
  env : 'dev'
  azureSubscription : 'corp-AIUtility-dev-cicd'
  deployAgentPoolName : 'ajg-corp-dev-win-agent' 

#Resource Name conventions common to all azure environments 
  serviceConnection : ''
  userRepository : ''
  resourceinfix : 'aiutility'
  regionshortname : 'eus2'
  resourceGroupName : 'corp-${{ variables.resourceinfix }}-main-rg' 

  backendApiAppServiceName : '' # not used
  backendFunctionAppName : 'corp-${{ variables.resourceinfix }}-function-${{ variables.env }}' # corp-aiutility-function-dev
 
  workspaceApiAppServiceName : 'corp-${{ variables.resourceinfix }}-workspace-webapp-${{ variables.env }}' #corp-aiutility-workspace-webapp-dev
  
  
  # botApiAppServiceName : ''
  # botServicesAppServiceName : ''
  # cliAppServiceName : ''

 